@extends('layouts.nav')

@section('title') Ticket @endsection
@section('contenet')
<div class="d-flex justify-content-center align-items-center vh-100">
    <div class="card shadow-lg p-4 rounded-3 bg-secondary-subtle" style="width: 60rem; max-width: 100%;">
        <div class="card-body text-center">
            <!-- User Name -->
            <h5 class="text-danger">Ticket for</h5>
            <h3 class="fw-bold text-dark">
                @if(session('user'))
                    <p>{{ session('user')->name }}</p>
                @endif
            </h3>
            <hr>

            <!-- Event Title -->
            <h2 class="fw-bold mb-3">{{ $event->title }}</h2>

            <!-- Event Description -->
            <p class="mb-3">{{ $event->description }}</p>

            <!-- Event Location -->
            <p class="fw-semibold">
                <i class="bi bi-geo-alt-fill"></i>
                {{ $event->location }}
            </p>

            <!-- Event Date & Time -->
            <p class="fw-bold text-danger">
                <i class="bi bi-calendar-event"></i>
                {{ \Carbon\Carbon::parse($event->dateTime)->format('l, d M Y - h:i A') }}
            </p>

            <hr>
            <p class="text-muted small">This ticket is generated by Event System</p>
        </div>
    </div>
</div>


@endsection